### ISSUE TITLE
Error when giving pip install

### ISSUE THREAD

**Issue by LipeTadeu** [embium/solverecaptchas#2]
Hi!
When doing pip install solverecaptchas,
gives error.
ERROR: Could not find a version that satisfies the requirement solverecaptchas (from versions: none)
ERROR: No matching distribution found for solverecaptchas

Is this lib pip?

Tks.

**Comment by embium** [comment]
Hello,

Yes this library is available under PyPI. Which version of Python are you using to install solverecaptchas under?

**Comment by LipeTadeu** [comment]
Hello 
my version is: Python 3.8.10

![erro](https://user-images.githubusercontent.com/26200412/158510642-6903ab23-575e-4ec2-853b-ee89373f4946.png)

**Comment by embium** [comment]
I was able to reproduce this on another machine - I'm not really sure why this is happening. A quick workaround is to install it using easy_install `python -m easy_install https://files.pythonhosted.org/packages/4b/40/9099b456dde3a98044190f608179ec419e9217f984935db2ae6ba57a831c/solverecaptchas-0.1.4-py3.10.egg`. I'll hope to have a fix here soon.

**Comment by LipeTadeu** [comment]
does it work on windows?

Nice, I hope you can fix it.

**Comment by LipeTadeu** [comment]
now this error.

C:\Users\lipet>python -m easy_install https://files.pythonhosted.org/packages/4b/40/9099b456dde3a98044190f608179ec419e9217f984935db2ae6ba57a831c/solverecaptchas-0.1.4-py3.10.egg
C:\Users\lipet\AppData\Local\Programs\Python\Python38\python.exe: No module named easy_install

**Comment by embium** [comment]
> does it work on windows?
> 
> Nice, I hope you can fix it.

Yes, this works for Windows. I've released another version that supports downloading through `pip`, in-case `pip install solverecaptchas` doesn't work, try `pip install https://files.pythonhosted.org/packages/f3/c5/33dbd5f793759dec4508a0cbc43955ea7e46c3b8072f26486efe9f5576eb/solverecaptchas-0.1.6.tar.gz`.

**Comment by LipeTadeu** [comment]
Hello Now generates these errors.
I believe there is content in the package to solve using audio.
I had understood that he solves via image.

d ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
ERROR (VoskAPI:Model():model.cc:122) Folder 'model' does not contain model files. Make sure you specified the model path properly in Model constructor. If you are not sure about relative path, use absolute path specification.
Traceback (most recent call last):
  File "teste.py", line 10, in <module>
    from solverecaptchas.solver import Solver
  File "C:\Users\lipet\AppData\Local\Programs\Python\Python38\lib\site-packages\solverecaptchas\solver.py", line 19, in <module>
    class Solver(object):
  File "C:\Users\lipet\AppData\Local\Programs\Python\Python38\lib\site-packages\solverecaptchas\solver.py", line 27, in Solver
    model=Model('model'),
  File "C:\Users\lipet\AppData\Local\Programs\Python\Python38\lib\site-packages\vosk\__init__.py", line 29, in __init__
    raise Exception("Failed to create a model")
Exception: Failed to create a model
